### PR TITLE
Updating board to match the instructor code repo

### PR DESCRIPTION
**Pull request by HalflingHelper**
There was no equals method in the student support code.

### CODE REVIEW

**Review by cty12 — COMMENTED** [review]
@jsiek Do you think it's a good idea to give the implementation of `Board.equals()` to the students? If we give it away, the first time a student gets exposed to implementing `equals()` seems to be the Next Prev Binary Tree lab.

**Comment by HalflingHelper** [comment]
My thought was that `equals` might be nice for them to have for testing, especially if they use assertEquals. Without the `equals` method it compares references and breaks.

Obviously they can always do string comparison so 🤷

**Comment by cty12** [comment]
Yes I think I agree. You'll probably want to explain what the `equals()` method does in lab, particularly because the students may not look at `Board.java`. I'll ask Prof. Siek and will merge if he agrees too!

**Comment by jsiek** [comment]
I think this change is a good one, thanks Calvin!

**Pull request merged**
